[build]
  command = "npm run build"
  publish = "build"
  
[[redirects]]
  from = "https://who-owns-mass.org"
  to = "https://whoownsmass.org"
  status = 301
  force = true

[[redirects]]
  from = "https://www.who-owns-mass.org"
  to = "https://whoownsmass.org"
  status = 301
  force = true
